echo ""
echo ""
echo "Removing old bash config files..."
echo ""
echo ""
rm -f ~/.bash_aliases && echo "Successfully removed ~/.bash_aliases"
rm -f ~/.bash_functions && echo "Successfully removed ~/.bash_functions"
rm -f ~/.bash_profile && echo "Successfully removed ~/.bash_profile"
rm -f ~/.bash_sessions_disable && echo "Successfully removed ~/.bash_sessions_disable"
rm -f ~/.bash-git-prompt && echo "Successfully removed ~/.bash-git-prompt"
rm -f ~/.bashrc && echo "Successfully removed ~/.bashrc"
rm -f ~/.dircolors && echo "Successfully removed ~/.dircolors"
rm -f ~/.dircolors-solarized && echo "Successfully removed ~/.dircolors-solarized"
rm -f ~/.git-prompt-colors.sh && echo "Successfully removed ~/.git-prompt-solarized"
rm -f ~/.inputrc && echo "Successfully removed ~/.inputrc"
echo ""
echo ""
echo "Successfully removed all old bash config files"
echo ""
echo ""
